// export default menu 
// const menu = [{
module.exports = [{
  "id": 1,
  "name": "工作台",
  "description": "工作台",
  "icon": "icon-user-name",
  "rightUrl": "workbench/workbenchAmount.do,workbench/commissionRemind.do,workbench/informationAnalyze.do,workbench/trendData.do,workbench/getAdminMessage.do",
  "pId": 0,
  "rightLevel": 1,
  "children": [],
  "state": "index",
  "path": "/contrDesk",
  "sort": 1
},
{
  "id": 2,
  "name": "企业管理",
  "description": "企业管理",
  "icon": "iconKehu01",
  "rightUrl": "",
  "pId": 0,
  "rightLevel": 1,
  "children": [{
    "id": 11,
    "name": "企业列表",
    "description": "企业列表",
    "rightUrl": "",
    "pId": 2,
    "rightLevel": 2,
    "children": [{
      "id": 17,
      "name": "全部企业",
      "description": "全部企业",
      "rightUrl": "user/selectUserList.do",
      "pId": 11,
      "rightLevel": 3,
      "children": [
      ],
      "state": "",
      "path": "/enterprise/enterpriseList/allEnterprise",
      "sort": 1
    }],
    "state": "customerList",
    "path": "/enterprise/enterpriseList",
    "sort": 1
  }],
  "state": "customer",
  "path": "/enterprise",
  "sort": 2
},
{
  "id": 3,
  "name": "运营管理",
  "description": "运营管理",
  "icon": "iconDingdan02",
  "rightUrl": "",
  "pId": 0,
  "rightLevel": 1,
  "children": [{
    "id": 12,
    "name": "帮助系统",
    "description": "帮助系统",
    "rightUrl": "",
    "pId": 3,
    "rightLevel": 2,
    "children": [{
      "id": 13,
      "name": "文章列表",
      "description": "文章列表",
      "rightUrl": "order/selectOrderXcxListInit.do,order/selectOrderXcxList.do",
      "pId": 12,
      "rightLevel": 3,
      "children": [],
      "state": "",
      "path": "/operate/help/helpList",
      "sort": 1
    },
    {
      "id": 13,
      "name": "帮助分类",
      "description": "帮助分类",
      "rightUrl": "order/selectOrderXcxListInit.do,order/selectOrderXcxList.do",
      "pId": 12,
      "rightLevel": 3,
      "children": [],
      "state": "",
      "path": "/operate/help/helpClassification",
      "sort": 1
    }],
    "state": "",
    "path": "/operate/help",
    "sort": 1
  },
  {
    "id": 37,
    "name": "广告管理",
    "description": "广告管理",
    "rightUrl": "",
    "pId": 3,
    "rightLevel": 2,
    "children": [{
      "id": 38,
      "name": "广告位",
      "description": "广告位",
      "rightUrl": "order/selectOrderMadeInit.do,order/selectOrderMadeList.do",
      "pId": 37,
      "rightLevel": 3,
      "children": [],
      "state": "",
      "path": "/operate/customorder/allCustomOrder",
      "sort": 1
    }],
    "state": "",
    "path": "/operate/customorder",
    "sort": 2
  }],
  "state": "order",
  "path": "/operate",
  "sort": 3
},
{
  "id": 4,
  "name": "财务管理",
  "description": "财务管理",
  "icon": "iconChanpin03",
  "rightUrl": "",
  "pId": 0,
  "rightLevel": 1,
  "children": [{
    "id": 59,
    "name": "续费明细",
    "description": "续费明细",
    "rightUrl": "",
    "pId": 4,
    "rightLevel": 2,
    "children": [{
      "id": 62,
      "name": "明细列表",
      "description": "明细列表",
      "rightUrl": "product/publishProductInit.do,product/publishProduct.do,industry/addOrUpdateIndustry.do,product/updateProductInit.do",
      "pId": 59,
      "rightLevel": 3,
      "children": [],
      "state": "product",
      "path": "/finance/renew/detailed",
      "sort": 1
    }],
    "state": "product",
    "path": "/finance/renew",
    "sort": 1
  },
  ],
  "state": "product",
  "path": "/finance",
  "sort": 4
},
{
  "id": 5,
  "name": "系统设置",
  "description": "系统设置",
  "icon": "iconYunying04",
  "rightUrl": "",
  "pId": 0,
  "rightLevel": 1,
  "children": [{
    "id": 74,
    "name": "系统设置",
    "description": "系统设置",
    "rightUrl": "",
    "pId": 5,
    "rightLevel": 2,
    "children": [{
      "id": 76,
      "name": "基本设置",
      "description": "基本设置",
      "rightUrl": "operation/selectDemandList.do,operation/selectDemandListInit.do,operation/updateDemandState.do",
      "pId": 74,
      "rightLevel": 3,
      "children": [],
      "state": "operation",
      "path": "/set/system/basic",
      "sort": 1
    }],
    "state": "operation",
    "path": "/set/system",
    "sort": 1
  },
  {
    "id": 75,
    "name": "权限设置",
    "description": "权限设置",
    "rightUrl": "",
    "pId": 5,
    "rightLevel": 2,
    "children": [{
      "id": 77,
      "name": "全部员工",
      "description": "全部员工",
      "rightUrl": "operation/serviceContractInit.do,operation/saveServiceContract.do",
      "pId": 75,
      "rightLevel": 3,
      "children": [],
      "state": "operation",
      "path": "/set/permission/allStaff",
      "sort": 1
    }],
    "state": "operation",
    "path": "/set/permission",
    "sort":2
  },
  {
    "id": 75,
    "name": "操作日志",
    "description": "操作日志",
    "rightUrl": "",
    "pId": 5,
    "rightLevel": 2,
    "children": [{
      "id": 77,
      "name": "日志记录",
      "description": "日志记录",
      "rightUrl": "operation/serviceContractInit.do,operation/saveServiceContract.do",
      "pId": 75,
      "rightLevel": 3,
      "children": [],
      "state": "operation",
      "path": "/set/operationLog/operationLog",
      "sort": 1
    }],
    "state": "operation",
    "path": "/set/operationLog",
    "sort": 3
  }],
  "state": "product",
  "path": "/set",
  "sort": 5
}
]